# print("welcome to tip calculator.\n")
# bill=input("what was you total bill?  : $")
# perc=input("what percentage tip would you like to pay?10 ,12 or 15?  :%")
# people=input("how many people would like to split the bill?  : ")
# cal1=float(perc)/100*float(bill)
# cal2=float(bill)/int(people)
# cal3=float(cal1)/int(people)
# tip=float(cal2)+float(cal3)
# print(f"each persons share is ${round(tip,2)}")
